// days_backoffice/pages/login/index.tsx
import Layout from '../../components/layout';

const LoginForm: React.FC = () => {

  const loginUser = async event => {
    event.preventDefault()

    const res = await fetch('/api/register', {
      body: JSON.stringify({
        name: event.target.name.value
      }),
      headers: {
        'Content-Type': 'application/json'
      },
      method: 'POST'
    });

    const result: JSON = await res.json();
    // result.user => 'Ada Lovelace'
  }

  return (
    <form onSubmit={loginUser} className="flex flex-col">
      <input type="email" id="txtEmail" name="txtEmail" placeholder="E-mail..." className="mx-auto rounded border-none w-1/5 h-10 pl-3 py-5 text-lg shadow focus:outline-none ring-2 ring-gray-500 focus:border-transparent" required />
      <input type="password" id="pswPassword" name="pswPassword" placeholder="Password..." className="mx-auto rounded border-none w-1/5 h-10 pl-3 py-5 mt-5 text-lg shadow focus:outline-none ring-2 ring-gray-500 focus:border-transparent" required />
      <p className="text-sm align-left mt-3">Esqueceu-se da password? Clique <a href="#" className="underline">aqui</a>!</p>
      <button type="submit" className="mx-auto mt-40 text-lg align-center text-gray-800 font-bold w-48 text-center py-3 rounded-lg border-2 border-solid border-gray-800 bg-white hover:bg-gray-800 hover:text-white transition duration-500 ease-in-out">L O G I N</button>
    </form>
  )
}


export default function Login() {
  return (
    <Layout>
      <div className="min-h-screen min-w-screen flex flex-col my-auto mx-auto justify-center text-center">
        <img src="logo.svg" alt="App logo" className="w-80 md:w-96 lg:w-96 mx-auto" />
        <p className="text-2xl md:text-3l lg:text-3xl mt-10">Faça <span className="font-bold">login</span> para usar o Days</p>
        <LoginForm />
        <p className="mt-3">Ainda não tem Days? Compre <a href="#" className="underline">aqui</a>!</p>
      </div>
    </Layout>
  )
}

// days_backoffice/pages/login/index.vue
<template>
  <div
    class="min-h-screen min-w-screen flex justify-center items-center text-center mx-auto"
  >
    <div>
      <Logo />
      <div class="w-46">
        <h1 class="text-3xl mt-10 text-gray-700 px-6 md:px-0">
          Faça <span class="font-bold">login</span> para ter acesso a um novo
          mundo de inovação escolar
        </h1>
      </div>
      <div class="mt-16 w-4/5 md:w-2/5 flex flex-col mx-auto">
        <form action="">
          <input
            type="email"
            placeholder="Introduza o seu e-mail..."
            class="shadow appearance-none border border-gray-500 rounded-md w-full py-3 px-3 text-gray-700 leading-tight focus:outline-none focus:border-green-100 focus:shadow-outline"
          />
          <input
            type="password"
            placeholder="Introduza a sua password..."
            class="mt-5 shadow appearance-none border border-gray-500 rounded-md w-full py-3 px-3 text-gray-700 leading-tight focus:outline-none focus:border-green-100 focus:shadow-outline"
          />
          <nuxt-link to="/">
            <p
              class="mt-4 text-sm hover:text-green-500 transition duration-600 ease-in-out text-left"
            >
              Esqueceu-se da password?
            </p>
          </nuxt-link>
          <nuxt-link to="/login">
            <p
              class="mt-16 border-gray-700 border-2 p-3 w-44 rounded-lg font-extrabold hover:bg-gray-700 hover:text-white hover:shadow-lg transition duration-500 ease-in-out mx-auto"
            >
              L O G I N
            </p>
          </nuxt-link>
          <nuxt-link to="/">
            <p
              class="mt-5 hover:text-green-500 transition duration-600 ease-in-out mx-auto"
            >
              V O L T A R
            </p>
          </nuxt-link>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import Vue from "vue";

export default Vue.extend({});
</script>

<style>
</style>
